version: '3.8'

services:
  app:
    image: cruelplatypus67/msg:0.3.0
    ports:
      - "80:80"
    environment:
      APP_DEBUG: False
      APP_PORT: 80
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msgdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


