# Packaging a django app with docker
# This uses poetry to install dependencies
# and then uses gunicorn to run the app


FROM python:3.7-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
RUN pip install poetry
COPY poetry.lock pyproject.toml /usr/src/app/
RUN poetry config virtualenvs.create false \
  && poetry install --no-dev

# Copy project
COPY . /usr/src/app/

# Run server
CMD gunicorn --bind